name: Profile

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0-23/3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
        submodules: "recursive"
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - run: sh build.sh

    - run: echo "gxb.pub" > dist/CNAME
    
    - name: Push to gh-pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        jekyll: false 
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
