name: Profile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0-23/3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i gitfolio -g
    - run: gitfolio build gggxbbb -f --theme dark --sort updated --order desc --background https://static.evax.top/img/bg.jpeg
    
    - name: Push to gh-pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        jekyll: false 
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
